version: '3.4'
x-var:
  - &DATABASE_USERNAME testuser
  - &DATABASE_PASSWORD testuser
volumes:
  basicOntimize-db-vol:
services:
  database:
    image: bitnami/postgresql:11.14.0-debian-10-r21
    environment:
      POSTGRESQL_DATABASE: basicOntimize
      POSTGRESQL_USERNAME: *DATABASE_USERNAME
      POSTGRESQL_PASSWORD: *DATABASE_PASSWORD
      POSTGRESQL_POSTGRES_PASSWORD: postgrespwd
    hostname: db.basicOntimize
    container_name: basicOntimize-db
    ports:
      - "5432:5432"
    volumes:
      - basicOntimize-db-vol:/bitnami/postgresql
