apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
{{- if .Values.podsLabels }}
{{ toYaml .Values.podsLabels | indent 6 }}
{{- end }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: VERSION
            value: {{ .Chart.Version }}
{{- range $pkey, $pval := .Values.env }}
          - name: {{ $pkey }}
            value: {{ quote $pval }}
{{- end }}
          - name: RELEASE_NAME
            value: {{ include "fullname" . }}
          - name: RELEASE_NAMESPACE
            value: {{ include "fullname" . }}
          - name: APPLICATION_NAME
            value: {{ .Values.service.name }}
          - name: HOST
            value: {{ .Values.ingress.host }}
        {{- if not .Values.tenantManager.enabled }}
          - name: DATABASE_SERVICE
            value: {{ .Values.database.service }}
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-db-secret" (include "fullname" .) }}
                key: user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-db-secret" (include "fullname" .) }}
                key: password
        {{- end }}
        {{- if .Values.tenantManagement.enabled }}
          - name: APP_DATABASE_SERVICE
            value: {{ .Values.database.service }}
          - name: APP_DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-db-secret" (include "fullname" .) }}
                key: adminuser
          - name: APP_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-db-secret" (include "fullname" .) }}
                key: adminpassword
        {{- end }}
        {{- if .Values.micrometer.metrics.tags.source }}
          - name: METRIC_TAG_SOURCE
            value: {{ .Values.micrometer.metrics.tags.source }}
        {{- end }}
        {{- if .Values.grafana.enabled }}
          - name: GRAFANA_SERVER
            value: {{ .Values.grafana.server }}
          - name: GRAFANA_ADMIN_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.grafana.secret | default (printf "%s-tm" (include "fullname" .))  }}
                key: apiKey
          - name: GRAFANA_DATASOURCE_NAME
            value: {{ .Values.grafana.datasourceName }}
        {{- end }}
        {{- if .Values.kafka.enabled }}
          - name: KAFKA_SERVER
            value: {{ .Values.kafka.server }}
          - name: KAKFA_SERVER
            value: {{ .Values.kafka.server }}
          - name: SCHEMA_REGISTRY_URL
            value: {{ .Values.kafka.schemaRegistryUrl }}
        {{- end }}
        {{- if .Values.tenantManager.enabled }}
          - name: TENANT_MANAGER
            value: {{ .Values.tenantManager.url }}
          - name: TENANT_MANAGER_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tenantManager.secret | default (printf "%stm-secret" (include "fullname" .))  }}
                key: user
          - name: TENANT_MANAGER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tenantManager.secret | default  (printf "%stm-secret" (include "fullname" .))  }}
                key: password
        {{- end }}
        {{- if .Values.tenantManagement.enabled }}
          - name: TENANT_MANAGER_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tenantManagement.secret | default (printf "%s-secret" (include "fullname" .))  }}
                key: user
          - name: TENANT_MANAGER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tenantManagement.secret | default  (printf "%s-secret" (include "fullname" .))  }}
                key: password
        {{- end }}
        {{- if .Values.s3.enabled }}
          - name: S3_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: {{ printf "%s-config" (include "fullname" .) }}
                key: s3-endpoint
          - name: S3_BUCKET
            valueFrom:
              configMapKeyRef:
                name: {{ printf "%s-config" (include "fullname" .) }}
                key: s3-bucket
          - name: S3_REGION
            valueFrom:
              configMapKeyRef:
                name: {{ printf "%s-config" (include "fullname" .) }}
                key: s3-region
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.s3.secret | default (printf "%s-s3-secret" (include "fullname" .))  }}
                key: accessKey
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.s3.secret | default  (printf "%s-s3-secret" (include "fullname" .))  }}
                key: secretKey
        {{- end }}
          - name: ENVIRONMENT_PROFILE
            valueFrom:
              configMapKeyRef:
                name: {{ printf "%s-config" (include "fullname" .) }}
                key: environment-profile
                optional: true
        {{- if .Values.ingress.tls }}
          - name: TLS
            value: enabled
        {{- end }}
        {{- if .Values.tenantManagement.enabled }}
          - name: KEYCLOAK_SERVICE
            valueFrom:
              configMapKeyRef:
                name: {{ printf "%s-config" (include "fullname" .) }}
                key: keycloak-service
          {{- if .Values.tenantManagement.advanced }}
          - name: KEYCLOAK_USERNAME
            value: {{ .Values.tenantManagement.keycloak.adminUser}}
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak
                key: admin-password
          {{- else }}
          - name: KEYCLOAK_AUTH_CLIENT
            valueFrom:
              configMapKeyRef:
                name: {{ printf "%s-config" (include "fullname" .) }}
                key: keycloak-auth-client
          - name: KEYCLOAK_AUTH_FRONT_CLIENT
            valueFrom:
              configMapKeyRef:
                name: {{ printf "%s-config" (include "fullname" .) }}
                key: keycloak-auth-front-client
          {{- end }}
        {{- end }}
          ports:
          - name: http
            containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.probePath | default .Values.probePath }}
              port: {{ .Values.probePort | default .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.probePath | default .Values.probePath }}
              port: {{ .Values.probePort | default .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
